### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by imSunnyk** [kaushikjadhav01/Stock-Market-Prediction-Web-App-using-Machine-Learning-And-Sentiment-Analysis#5]
Hello bro,

It's asking for WordPress login JKS

what's the login and password
I checked in WordPress named MySQL db it's showing three credentials for users but password has not been working....
Please suggest

And also I had to install tensorflow 2.2.0 
Because tensorflow 1.14 didnot have matching distribution

But please tell something about llogin after import** login ** for jks has come...but unable to login

and in wordpress JKS login this warning is there

Warning: Declaration of QuietSkin::feedback($string) should be compatible with WP_Upgrader_Skin::feedback($string, ...$args) in /opt/lampp/htdocs/testsite/wp-content/plugins/ocean-extra/includes/wizard/classes/QuietSkin.php on line 12

**Comment by imSunnyk** [comment]
And which virsion of python you used?

**Comment by imSunnyk** [comment]
The above issue is not resolving...
The wordpress login unable to be done....

After all setup it's now showing 
Localhost/site/wplogin  wordpress for his but MySQL db credentials is not being taken ....

**Comment by kaushikjadhav01** [comment]
Hi,

Sorry for the delay in responding as I have been busy with my professional life since many months, I have updated my code and it is working fine now. Please remove all packages and code from your local machine, take a fresh copy of my project from github, install all packages and set it up. If you still run into issues, please reach out to me.

Regards, 
Kaushik Jadhav
