### ISSUE TITLE
Error establishing a database connection

### ISSUE THREAD

**Issue by pulak31** [kaushikjadhav01/Stock-Market-Prediction-Web-App-using-Machine-Learning-And-Sentiment-Analysis#9]
when I try to open http://localhost/www/wordpress-5.6.2/wordpress/, it says error establishing a database connection.
![database](https://user-images.githubusercontent.com/75310992/109520314-193bc380-7ad2-11eb-96df-ae5db6b6b463.PNG)

**Comment by kaushikjadhav01** [comment]
Hi,

This happened because I had missed one step in the installation instructions. Extremely sorry for the inconvenience. I had missed out the step for admin user account creation. Please follow the new installation steps and try again. Also please make sure that you have Python 3.8.5 installed. For python 3.9, there is no support for tensorflow and the machine learning models might not work as expected.

Regards,
Kaushik Jadhav
